all:
    hosts:
        nuvo0:
        nuvo1:
        nuvo2:
        cas0:
        cas1:
        cas2:
        cas3:
        guibox:
        uas:
        uas0:
        uas1:
        uas2:
    vars:
      kamera_dir: "/home/user/kw/kamera" # Where the git repo is located
      data_dir: "/mnt/flight_data" # Where the flight data is stored
      ansible_user: user

    children:
        taiga:
            hosts:
                nuvo0:
                  redis_host: true
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/leader/supervisor.conf"
                  leader: True
                  follower: False
                  gui: True
                  # /dev/disk/by-uuid
                  ssd_id: "ca0a9985-84ac-4019-95a6-242d3c81c86d"
                nuvo1:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/follower/supervisor.conf"
                  leader: False
                  follower: True
                  ssd_id: "d31ab8b6-b273-49c3-bd32-56c4fb76219c"
                nuvo2:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/follower/supervisor.conf"
                  leader: False
                  follower: True
                  ssd_id: "883fec5d-e6a2-454a-8239-438e2fbc56c3"
            vars:
                gui: False
                config_dir: "taiga"
                nvidia_cuda: True
        uav:
            hosts:
                guibox:
                  redis_host: false
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/gui/supervisor.conf"
                  leader: False
                  follower: False
                uas0:
                  redis_host: true
                  external_disk_label: uas0_center
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/leader/supervisor.conf"
                  leader: True
                  follower: False
                uas1:
                  redis_host: false
                  external_disk_label: uas1_left
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/follower/supervisor.conf"
                  leader: False
                  follower: True
                uas2:
                  redis_host: false
                  external_disk_label: uas2_right
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/follower/supervisor.conf"
                  leader: False
                  follower: True
            vars:
                nvidia_cuda: False
        cas:
            hosts:
                cas0:
                  redis_host: true
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/leader/supervisor.conf"
                  leader: True
                  follower: False
                  ssd_id: "3ca48dde-3b0f-440a-bbc2-69e6bd559325"
                cas1:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/follower/supervisor.conf"
                  leader: False
                  follower: True
                  ssd_id: "40d83577-292f-4795-b275-9b3c38504c22"
                cas2:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/follower/supervisor.conf"
                  leader: False
                  follower: True
                  ssd_id: "1b5b6c41-48f2-43fe-82db-fdc598387ea3"
                cas3:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/{{ config_dir }}/leader/supervisor.conf"
                  leader: True
                  follower: False
                  ssd_id: "TODO"
            vars:
                gui: False
                config_dir: "taiga"
                nvidia_cuda: True
