all:
    hosts:
        nuvo0:
        nuvo1:
        nuvo2:
        cas0:
        cas1:
        cas2:
        cas3:
        guibox:
        uas:
        uas0:
        uas1:
        uas2:
    vars:
      kamera_dir: "/home/user/kw/kamera" # Where the git repo is located
      data_dir: "/mnt/flight_data" # Where the flight data is stored
      ansible_user: user

    children:
        nuvos:
            hosts:
                nuvo0:
                  redis_host: true
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/leader/supervisor.conf"
                  leader: True
                  follower: False
                nuvo1:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/follower/supervisor.conf"
                  leader: False
                  follower: True
                nuvo2:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/follower/supervisor.conf"
                  leader: False
                  follower: True
            vars:
                nvidia_cuda: True
                gui: False
        uav:
            hosts:
                guibox:
                  redis_host: false
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/gui/supervisor.conf"
                  leader: False
                  follower: False
                uas0:
                  redis_host: true
                  external_disk_label: uas0_center
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/leader/supervisor.conf"
                  leader: True
                  follower: False
                uas1:
                  redis_host: false
                  external_disk_label: uas1_left
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/follower/supervisor.conf"
                  leader: False
                  follower: True
                uas2:
                  redis_host: false
                  external_disk_label: uas2_right
                  supervisor_file: "{{ kamera_dir }}/tmux/uas/follower/supervisor.conf"
                  leader: False
                  follower: True
            vars:
                nvidia_cuda: False
        cas:
            hosts:
                cas0:
                  redis_host: true
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/leader/supervisor.conf"
                  leader: True
                  follower: False
                  ssd_id: "TODO_insert_ssd_id_from_ls_byuid"
                cas1:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/follower/supervisor.conf"
                  leader: False
                  follower: True
                  ssd_id: "TODO_insert_ssd_id_from_ls_byuid"
                cas2:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/follower/supervisor.conf"
                  leader: False
                  follower: True
                  ssd_id: "TODO_insert_ssd_id_from_ls_byuid"
                cas3:
                  redis_host: False
                  supervisor_file: "{{ kamera_dir }}/tmux/cas/follower/supervisor.conf"
                  leader: True
                  follower: False
                  ssd_id: "TODO_insert_ssd_id_from_ls_byuid"
            vars:
                nvidia_cuda: True
                gui: False
