[tool.poetry]
name = "kamera"
version = "0.1.0"
description = "KAMERA: Kitware's Image Acquisition ManagER and Archiver"
authors = ["Adam Romlein <adam.romlein@kitware.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.1.1"
scipy = "^1.14.1"
matplotlib = "^3.9.2"
opencv-python = "^4.10.0.84"
pillow = "^10.4.0"
pyyaml = "^6.0.2"
datetime = "^5.5"
exifread = "^3.0.0"
pygeodesy = "^24.9.29"
pyshp = "^2.3.1"
simplekml = "^1.3.6"
shapely = "^2.0.6"
transformations = "^2024.5.24"
scriptconfig = "^0.8.0"
ubelt = "^1.3.6"
rich = "^13.9.1"
gdal = {url = "https://github.com/girder/large_image_wheels/raw/wheelhouse/GDAL-3.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=0ccdfd68893818a86d2225c1efe6b4a64a6d84676f6fb1e7ec5a4138f70d837b"}
ipdb = "^0.13.13"
bottle = "^0.13.2"
pycolmap = "^3.11.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
