[program:kamerad]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh kamerad
user=user
autostart=false

[program:image_manager]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh image_manager
user=user
autostart=false

[program:mount_nas]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/mount_nas.sh
startsecs=0
user=root
autostart=true

[program:host_shutdown]
command=/bin/bash /home/user/kw/kamera/provision/start_stop/host_shutdown.sh
startsecs=0
user=root
autostart=false
autorestart=false

[program:host_reboot]
command=/bin/bash /home/user/kw/kamera/provision/start_stop/host_reboot.sh
startsecs=0
user=root
autostart=false
autorestart=false

[program:cam_ir]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh cam_ir
user=user
autostart=false

[program:cam_uv]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh cam_uv
user=user
autostart=false

[program:cam_rgb]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh cam_rgb
user=user
autostart=false

[program:imageview]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh imageview
user=user
autostart=false

[program:fps_monitor]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh fps_monitor
user=user
autostart=false

[program:detector]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh detector
user=user
autostart=false

[program:flight_summary]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh flight_summary
user=user
autostart=false

[program:homography]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh homography
user=user
autostart=false

[program:detections]
command=/bin/bash /home/user/kw/kamera/tmux/nayak/follower/start_tmux_session.sh detections
user=user
autostart=false

[group:nayak]
programs=cam_ir,cam_uv,cam_rgb,imageview,detector,fps_monitor

[group:postproc]
programs=flight_summary,detections,homography
