#!/usr/bin/env bash

# Run this script as sudo, then reboot

printf "
# Auto-generated by kamera/src/run_scripts/disable_nouveau.sh
blacklist nouveau
blacklist lbm-nouveau
options nouveau modeset=0
alias nouveau off
alias lbm-nouveau off
" >> /etc/modprobe.d/kamera-disable-nouveau.conf

update-initramfs -u
