<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>backend</name>
  <version>1.0.0</version>
  <description>
    High level package to install all the backend dependencies
  </description>

  <maintainer email="adam.romlein@kitware.com">Adam Romlein</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>custom_msgs</exec_depend>
  <exec_depend>roskv</exec_depend>
  <exec_depend>kamcore</exec_depend>
  <exec_depend>ins_driver</exec_depend>
  <exec_depend>mcc_daq</exec_depend>
  <exec_depend>ser_daq</exec_depend>
  <exec_depend>nexus</exec_depend>
  <exec_depend>view_server</exec_depend>
  <exec_depend>cam_utils</exec_depend>
  <exec_depend>prosilica_camera</exec_depend>
  <exec_depend>kw_genicam_driver</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
