<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>bag_file_explode</name>
  <version>1.0.0</version>
  <description>Explode legacy bag files into images + nav yaml (uses the rosbags library)</description>

  <maintainer email="adam.romlein@kitware.com">Adam Romlein</maintainer>
  <author>Adam Romlein</author>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
