# Playbook for properly configuring individual systems
- hosts: all
  tasks:
    - name: Make nuvo images
      command:
        chdir: "{{ kamera_dir }}"
        cmd: make nuvo

    - name: Make viame images
      command:
        chdir: "{{ kamera_dir }}"
        cmd: make viame
    
    - name: Make postflight images
      command:
        chdir: "{{ kamera_dir }}"
        cmd: make postflight

    - name: Clean dangling images
      command:
        cmd: docker system prune -f
