# Playbook for properly configuring individual systems
- hosts: all
  tasks:
    - name: Make leader images
      command:
        chdir: "{{ kamera_dir }}"
        cmd: make leader
        when: leader

    - name: Make follower images
      command:
        chdir: "{{ kamera_dir }}"
        cmd: make follower
        when: follower

    - name: Clean dangling images
      command:
        cmd: docker system prune -f
