---
## Auxiliary node to attach to master
version: '3.7'
services:
  ## =========================== headless nodes =============================
  cam_rgb:
    container_name: "cam-rgb-${CAM_FOV}"
    image: "gitlab.kitware.com:4567/noaa_uav/noaa_kamera/kamera/${ROS_DISTRO}:${TAG_CAM_RGB:-latest}"
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      ROS_DISTRO: "noetic"
      REDIS_HOST: "${REDIS_HOST}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_MODE: "rgb"
      CAM_FOV: "${CAM_FOV}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "/home/user/kw/noaa_kamera/src/run_scripts/entry:/entry"
      - "${KAMERA_DIR}:/root/noaa_kamera"
    entrypoint: ["/bin/tini", "--"]
    command: ["/entry/cam_phaseone.sh"]
    restart: always
...
