---
## Auxiliary node to attach to master
version: '3.7'
services:
  cam_ir:
    container_name: "cam-ir-${CAM_FOV}"
    image: kitware/kamera:core
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      ROS_DISTRO: "noetic"
      REDIS_HOST: "${REDIS_HOST}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_MODE: "ir"
      CAM_FOV: "${CAM_FOV}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/cam_ir.sh"]
    restart: unless-stopped
...
