---
## Auxiliary node to attach to master
version: '3.7'
services:
  ## =========================== headless nodes =============================
  cam_rgb:
    container_name: "cam-rgb-${CAM_FOV}"
    image: kitware/kamera:core
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      ROS_DISTRO: "noetic"
      REDIS_HOST: "${REDIS_HOST}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_MODE: "rgb"
      CAM_FOV: "${CAM_FOV}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/cam_phaseone.sh"]
        #command: ["bash"]
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
...
