---
## Auxiliary node to attach to master
version: '3.7'
services:
  ## =========================== headless nodes =============================
  cam_uv:
    container_name: "cam-uv-${CAM_FOV}"
    image: kamera/final/core-cudaon
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      REDIS_HOST: "${REDIS_HOST}"
      ROS_DISTRO: "noetic"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_MODE: "uv"
      CAM_FOV: "${CAM_FOV}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${KAMERA_DIR}/src:ro"
        #    command: ["bash"]
    command: ["/entry/cam_prosilica.sh", "uv"]
    restart: always
...
