---
## Core processes
version: '3.7'
services:
  cam_param_monitor:
    container_name: cam_param_monitor
    image: kitware/kamera:core
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      REDIS_HOST: "${REDIS_HOST}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/cam_param_monitor.sh"]
    restart: unless-stopped
...
