---
## Bring up the core nodes (aside from roscore)
version: '3.7'
services:
  daq:
    container_name: daq
    image: kamera/final/core-cudaon
    tty: true
    devices:
      - "${MCC_DAQ}:${MCC_DAQ}"
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      MCC_DAQ: "${MCC_DAQ}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/daq.sh"]
    restart: unless-stopped
...
