---
## container configuration for viame interactive building
# use compose v2 to use runtime config
version: '2.4'

services:
## ========================== viame =============================
  detector:
    container_name: "viame-${CAM_FOV}"
    image: kitware/kamera:viame
    tty: true
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME:-}"
      PRODUCER_HOST: "${PRODUCER_HOST:-}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      PIPEFILE: "${PIPEFILE}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    restart: on-failure
    command: ["/entry/viame.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
...
