---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  detections:
    image: kitware/kamera:postproc
    network_mode: host
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_FOV: "${CAM_FOV}"
    tty: true
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
      - "${PWD}/src/run_scripts/entry:/entry:ro"
    entrypoint: ["/entry/postproc_detections.sh"]
