---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  detections:
    image: kamera/final/postproc
    network_mode: host
    tty: true
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${KAMERA_DIR}/src:ro"
    entrypoint: ["/entry/postproc_detections.sh"]
