---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  flight_summary:
    image: kitware/kamera:postproc
    network_mode: host
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_FOV: "${CAM_FOV}"
    tty: true
    volumes:
      - "/mnt:/mnt"
      - "${KAMERA_DIR}/src/run_scripts/entry:/entry"
      - "${KAMERA_DIR}:${DOCKER_KAMERA_DIR}:ro"
      - "${KAMERA_DIR}/kamera:/src/kamera/kamera:ro"
    entrypoint: ["/entry/postproc_summary.sh"]
