---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  flight_summary:
    image: kamera/final/postproc
    network_mode: host
    tty: true
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src/run_scripts/entry:/entry"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    entrypoint: ["/entry/postproc_summary.sh"]
