---
## container configuration for GUI
version: '3.7'
services:
## =========================== gui =============================
  gui:
    container_name: gui
    image: kitware/kamera:gui
    tty: true
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      ROS_IP: "${ROS_IP:-}"
      ROS_HOSTNAME: "${ROS_HOSTNAME:-}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      GUI_CFG_DIR: "${GUI_CFG_DIR}"
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
      START_IN_SHELL: "${START_IN_SHELL}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/home/user/kw/kamera/scripts:/home/user/kamera_ws/scripts"
      - "${PWD}/src:/home/user/kamera_ws/src:ro"
      - "${PWD}/assets:/home/user/noaa_kamera/assets:ro"
      - "/home/user/kw/kamera/src/kitware-ros-pkg/wxpython_gui/:/home/user/kamera_ws/src/kitware-ros-pkg/wxpython_gui"
      - "save-gui:/home/user/.config/kamera/gui"
      - "${HOME}/.ssh:/home/user/.ssh"
    entrypoint: ["/bin/tini", "--"]
    command: ["/entry/gui.sh"]
    #command: ["bash"]

volumes:
  save-gui:
    name: save-gui
    labels:
      com.kitware.description: "Persistence for saved data from GUI, e.g. config state"
    driver: local
    driver_opts:
      type: none
      o: "bind,uid=1000"
      device: "${HOME}/.config/kamera/gui"
...
