---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  homography:
    image: kitware/kamera:postproc
    network_mode: host
    tty: true
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    entrypoint: ["/entry/postproc_homography.sh"]
