---
## Auxiliary node to attach to master
version: '3.7'
services:
  ## =========================== headless nodes =============================
  image_manager:
    container_name: "image_manager"
    image: kamera/final/core-cudaon
    tty: true
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:$DOCKER_KAMERA_DIR/src:ro"
    command: ["/entry/image_manager.sh"]
    restart: always
...
