---
## Bring up the process nodes (nexus, debayer, imageview)
version: '3.7'
services:
  imageview:
    container_name: "imageview-${CAM_FOV}"
    image: "gitlab.kitware.com:4567/noaa_uav/noaa_kamera/kamera/${ROS_DISTRO}:${BRANCH:-latest}"
    tty: true
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      CAM_FOV: "${CAM_FOV}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${KAMERA_DIR}:/root/noaa_kamera"
    entrypoint: [ "/bin/tini", "--" ]
    command: ["/entry/imageview.sh"]
    restart: on-failure
## ====================================================================
...
