---
## Bring up the core nodes (aside from roscore)
version: '3.7'
services:
  ins:
    container_name: ins
    image: gitlab.kitware.com:4567/noaa_uav/noaa_kamera/kamera/${ROS_DISTRO}:latest
    tty: true
    devices:
      - "${PULSE_TTY}:${PULSE_TTY}"
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      ALLOW_SERIAL_INS_SPOOF: "${ALLOW_SERIAL_INS_SPOOF}"
      SPOOF_INS: "${SPOOF_INS}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      PULSE_TTY: "${PULSE_TTY}"
      CLOCK_SKEW: "0.0"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${KAMERA_DIR}:/root/noaa_kamera"
    entrypoint: [ "/bin/tini", "--" ]
    command: ["/entry/ins.sh"]
    restart: always
...
