---
## Core processes
services:
  ## =========================== headless nodes =============================
  kamerad:
    image: ${KAMERA_KAMERAD_IMAGE}
    init: true
    network_mode: host
    build: ../src/core/kamerad
    tty: true
    user: root
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
    volumes:
        - "/mnt:/mnt:ro,rshared"
    restart: unless-stopped
...
