---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  kamerad:
    image: kitware/kamera:kamerad
    network_mode: host
    build: ../src/core/kamerad
    tty: true
    user: root
    volumes:
        - "/mnt:/mnt:ro,rshared"
    restart: unless-stopped
...
