---
## Diagnostics / quality testing
services:
  ## =========================== headless nodes =============================
  nodelist:
    container_name: nodelist
    image: kitware/kamera:core
    tty: true
    network_mode: host
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
    volumes:
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
      - "${PWD}/src/run_scripts/entry:/entry:ro"
    command: ["/entry/rosnode_list.sh"]
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
...

