---
## Diagnostics / quality testing
version: '3.7'
services:
  ## =========================== headless nodes =============================
  nodelist:
    container_name: nodelist
    image: gitlab.kitware.com:4567/noaa_uav/noaa_kamera/kamera/${ROS_DISTRO}:latest
    tty: true
    network_mode: host
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      SPOOF_RATE: "${SPOOF_RATE}"
    volumes:
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/rosnode_list.sh"]
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
...

