---
## Core processes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  postproc:
    image: gitlab.kitware.com:4567/noaa_uav/noaa_kamera/postproc:latest
    network_mode: host
    tty: true
    volumes:
        - "/mnt:/mnt"
        - "$PWD/../kamera/postflight:/src/postflight"
        - "$PWD/../src/run_scripts/entry:/entry"
        - "$PWD/../tmux/cas/env.sh:/entry/env.sh"
