---
## Bring up the core nodes
version: '3.7'
services:
  ## =========================== headless nodes =============================
  roscore:
    container_name: roscore
    image: kitware/kamera:core
    tty: true
    network_mode: host
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
      SPOOF_RATE: "${SPOOF_RATE}"
      REDIS_HOST: "${REDIS_HOST}"
      SYSTEM_NAME: "${SYSTEM_NAME}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/master.sh"]
    restart: unless-stopped
...

