---
## Core processes
version: '3.7'
services:
  shapefile_monitor:
    container_name: shapefile_monitor
    image: kamera/final/core-cudaon
    tty: true
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      DOCKER_KAMERA_DIR: "${DOCKER_KAMERA_DIR}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
    command: ["/entry/shapefile_monitor.sh"]
    restart: unless-stopped
...
