---
## Core processes
version: '3.7'
services:
  shapefile_monitor:
    container_name: shapefile_monitor
    image: "gitlab.kitware.com:4567/noaa_uav/noaa_kamera/kamera/${ROS_DISTRO}:${TAG_KAMERA_SHAPEFILE:-latest}"
    tty: true
    environment:
      REDIS_HOST: "${REDIS_HOST}"
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME}"
      KAMERA_DIR: "${KAMERA_DIR}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/home/user/kw/noaa_kamera/src:/root/kamera_ws/src"
      - "${PWD}/src:${PROJ_DIR}/src:ro"
    entrypoint: ["/bin/tini", "--"]
    command: ["/entry/shapefile_monitor.sh"]
    restart: always
...
