---
version: "2.4"
## =======================image sync publisher===================
services:
  sync-publisher:
    container_name: "sync-publisher-${CAM_FOV}"
    image: "gitlab.kitware.com:4567/noaa_uav/noaa_kamera/final/viame-kamera:cuda10.2"
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME:-}"
      ROS_IP: "${ROS_IP:-}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "${DATA_MOUNT_POINT}:${DATA_MOUNT_POINT}"
      - "${HOME}:${HOME}:ro"
      - "${PWD}/src:/src/noaa_kamera/src"
      # this should point to whatever publish_sync_msgs.sh expects
      - "/mnt/data:/mnt/data/calibration_2020_fl08"
    entrypoint: ["/tini", "--"]
    command: ["/entry/publish_sync_msgs.sh"]
...
