---
version: "3.7"
## =======================image sync publisher===================
services:
  sync-publisher:
    container_name: "sync-publisher-${CAM_FOV}"
    image: kamera/final/viame
    tty: true
    environment:
      ROS_MASTER_URI: "${ROS_MASTER_URI}"
      NODE_HOSTNAME: "${NODE_HOSTNAME:-}"
      ROS_IP: "${ROS_IP:-}"
      DATA_MOUNT_POINT: "${DATA_MOUNT_POINT}"
    dns:
      - "${KAMERA_DNS_IP}"
    dns_search:
      - kamera.systems
    network_mode: host
    volumes:
      - "/mnt:/mnt"
      - "${PWD}/src:${DOCKER_KAMERA_DIR}/src:ro"
      - "${HOME}:${HOME}:ro"
      # this should point to whatever publish_sync_msgs.sh expects
      - "/mnt/data:/mnt/data/calibration_2020_fl08"
    command: ["/entry/publish_sync_msgs.sh"]
...
