<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>sensor_simulator</name>
  <version>1.0.0</version>
  <description>Simulated camera / INS message sources for development</description>

  <maintainer email="adam.romlein@kitware.com">Adam Romlein</maintainer>
  <author email="matt.brown@kitware.com">Matt Brown</author>
  <license>Apache 2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>custom_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>python3-numpy</exec_depend>

  <export>
    <architecture_independent/>
    <build_type>ament_python</build_type>
  </export>
</package>
