<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>prosilica_camera</name>
  <version>2.0.0</version>
  <description>A ROS2 driver node for AVT/Prosilica Gigabit Ethernet (GigE) cameras.</description>
  <maintainer email="adam.romlein@kitware.com">Adam Romlein</maintainer>

  <license>BSD</license>

  <url type="website">http://www.ros.org/wiki/prosilica_camera</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>sensor_msgs</depend>
  <depend>custom_msgs</depend>
  <depend>image_transport</depend>
  <depend>camera_calibration_parsers</depend>
  <depend>cv_bridge</depend>
  <depend>cam_utils</depend>
  <depend>roskv</depend>
  <depend>prosilica_gige_sdk</depend>
  <depend>libopencv-dev</depend>
  <depend>nlohmann-json-dev</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
